// proquip_new/frontend/src/components/Dashboard.tsx
'use client'

import { useEffect, useState } from 'react'
import styles from './Dashboard.module.css'

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8280'

interface Summary {
  totalProducts: number
  activeSuppliers: number
  pendingOrders: number
  lowStockItems: number
  pendingApprovals: number
}

interface RecentOrder {
  id: number
  orderNumber: string
  supplierName: string
  totalAmount: number
  status: string
  orderDate: string
}

interface SpendingTrend {
  month: string
  amount: number
}

interface CategorySpending {
  categoryName: string
  orderCount: number
  totalAmount: number
}

interface LowStockItem {
  id: number
  productId: number
  productName: string
  productSku: string
  quantity: number
  minimumStock: number
  status: string
}

interface Budget {
  id: number
  name: string
  totalAmount: number
  usedAmount: number
}

const STATUS_LABELS: Record<string, string> = {
  DRAFT: '下書き',
  SUBMITTED: '提出済',
  PENDING_APPROVAL: '承認待ち',
  APPROVED: '承認済',
  REJECTED: '却下',
  ORDERED: '発注済',
  RECEIVED: '受入済',
  CANCELLED: 'キャンセル',
  CLOSED: '完了',
}

const STATUS_CLASSES: Record<string, string> = {
  DRAFT: 'statusDraft',
  SUBMITTED: 'statusPending',
  PENDING_APPROVAL: 'statusPending',
  APPROVED: 'statusApproved',
  REJECTED: 'statusRejected',
  ORDERED: 'statusOrdered',
  RECEIVED: 'statusCompleted',
  CANCELLED: 'statusCancelled',
  CLOSED: 'statusCompleted',
}

function formatCurrency(amount: number | null): string {
  if (amount == null) return '¥0'
  return '¥' + amount.toLocaleString('ja-JP')
}

function formatDate(dateStr: string | null): string {
  if (!dateStr) return '-'
  const d = new Date(dateStr)
  if (isNaN(d.getTime())) return '-'
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}年${m}月${day}日`
}

export function Dashboard() {
  const [summary, setSummary] = useState<Summary | null>(null)
  const [recentOrders, setRecentOrders] = useState<RecentOrder[]>([])
  const [spendingTrend, setSpendingTrend] = useState<SpendingTrend[]>([])
  const [categorySpending, setCategorySpending] = useState<CategorySpending[]>([])
  const [lowStockItems, setLowStockItems] = useState<LowStockItem[]>([])
  const [budgets, setBudgets] = useState<Budget[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const loadData = () => {
    setLoading(true)
    setError('')

    Promise.all([
      fetch(`${API_BASE}/api/dashboard/summary`).then(r => r.json()),
      fetch(`${API_BASE}/api/dashboard/recent-orders`).then(r => r.json()),
      fetch(`${API_BASE}/api/dashboard/spending-trend`).then(r => r.json()),
      fetch(`${API_BASE}/api/dashboard/category-spending`).then(r => r.json()),
      fetch(`${API_BASE}/api/dashboard/low-stock-items`).then(r => r.json()),
      fetch(`${API_BASE}/api/dashboard/budgets`).then(r => r.json()),
    ])
      .then(([s, orders, trend, cats, stock, b]) => {
        setSummary(s)
        setRecentOrders(orders)
        setSpendingTrend(trend)
        setCategorySpending(cats)
        setLowStockItems(stock)
        setBudgets(b)
        setLoading(false)
      })
      .catch(() => {
        setError('データの取得に失敗しました。再度お試しください。')
        setLoading(false)
      })
  }

  useEffect(() => { loadData() }, [])

  const budgetTotal = budgets.reduce((s, b) => s + (b.totalAmount || 0), 0)
  const budgetSpent = budgets.reduce((s, b) => s + (b.usedAmount || 0), 0)
  const budgetUtilization = budgetTotal > 0 ? Math.round((budgetSpent / budgetTotal) * 100) : 0

  const maxSpending = Math.max(...spendingTrend.map(d => d.amount || 0), 1)
  const totalCategoryAmount = categorySpending.reduce((s, c) => s + (c.totalAmount || 0), 0)

  if (loading) {
    return <div className={styles.loading}>読み込み中...</div>
  }

  return (
    <div>
      <div className={styles.pageHeader}>
        <h1 className={styles.pageTitle}>ダッシュボード</h1>
        <p className={styles.pageDescription}>調達・在庫管理の概況</p>
      </div>

      {error && (
        <div className={styles.errorBanner}>
          <span>⚠ {error}</span>
          <button className={styles.btnRetry} onClick={loadData}>再試行</button>
        </div>
      )}

      {/* サマリーカード */}
      <section className={styles.summaryCards}>
        <div className={`${styles.summaryCard} ${styles.cardOrders}`}>
          <div className={styles.cardHeader}>
            <h3 className={styles.cardTitle}>商品数</h3>
          </div>
          <div className={styles.cardMainValue}>{summary?.totalProducts ?? 0}</div>
          <div className={styles.cardDescription}>有効な商品数</div>
        </div>

        <div className={`${styles.summaryCard} ${styles.cardStock}`}>
          <div className={styles.cardHeader}>
            <h3 className={styles.cardTitle}>在庫アラート</h3>
          </div>
          <div className={`${styles.cardMainValue} ${(summary?.lowStockItems ?? 0) > 0 ? styles.alertValue : ''}`}>
            {summary?.lowStockItems ?? 0}
          </div>
          <div className={styles.cardDescription}>在庫不足の製品</div>
        </div>

        <div className={`${styles.summaryCard} ${styles.cardApprovals}`}>
          <div className={styles.cardHeader}>
            <h3 className={styles.cardTitle}>承認待ち</h3>
          </div>
          <div className={`${styles.cardMainValue} ${(summary?.pendingApprovals ?? 0) > 0 ? styles.pendingValue : ''}`}>
            {summary?.pendingApprovals ?? 0}
          </div>
          <div className={styles.cardDescription}>承認が必要なタスク</div>
        </div>

        <div className={`${styles.summaryCard} ${styles.cardBudget}`}>
          <div className={styles.cardHeader}>
            <h3 className={styles.cardTitle}>予算消化率</h3>
          </div>
          <div className={styles.cardMainValue}>{budgetUtilization}%</div>
          <div className={styles.budgetBar}>
            <div
              className={`${styles.budgetBarFill} ${budgetUtilization > 95 ? styles.budgetDanger : budgetUtilization > 80 ? styles.budgetWarning : ''}`}
              style={{ width: `${Math.min(budgetUtilization, 100)}%` }}
            />
          </div>
          <div className={styles.budgetDetail}>
            {formatCurrency(budgetSpent)} / {formatCurrency(budgetTotal)}
          </div>
        </div>
      </section>

      {/* チャートセクション */}
      <section className={styles.chartsSection}>
        <div className={styles.chartContainer}>
          <h3 className={styles.sectionTitle}>月別発注金額推移</h3>
          <div className={styles.chartBars}>
            {spendingTrend.map((item) => (
              <div key={item.month} className={styles.chartBarWrapper}>
                <div
                  className={styles.chartBar}
                  style={{ height: `${(item.amount / maxSpending) * 200}px` }}
                  title={`${item.month}: ${formatCurrency(item.amount)}`}
                />
                <span className={styles.chartBarLabel}>
                  {item.month ? item.month.slice(5) : ''}
                </span>
              </div>
            ))}
            {spendingTrend.length === 0 && (
              <div className={styles.emptyState}>データがありません</div>
            )}
          </div>
        </div>

        <div className={styles.chartContainer}>
          <h3 className={styles.sectionTitle}>カテゴリ別支出割合</h3>
          <div className={styles.categoryList}>
            {categorySpending.map((item) => {
              const pct = totalCategoryAmount > 0
                ? Math.round((item.totalAmount / totalCategoryAmount) * 100) : 0
              return (
                <div key={item.categoryName} className={styles.categoryItem}>
                  <span className={styles.categoryName}>{item.categoryName}</span>
                  <div className={styles.categoryBar}>
                    <div className={styles.categoryBarFill} style={{ width: `${pct}%` }} />
                  </div>
                  <span className={styles.categoryPct}>{pct}%</span>
                  <span className={styles.categoryAmount}>{formatCurrency(item.totalAmount)}</span>
                </div>
              )
            })}
            {categorySpending.length === 0 && (
              <div className={styles.emptyState}>データがありません</div>
            )}
          </div>
        </div>
      </section>

      {/* 詳細セクション */}
      <section className={styles.detailSection}>
        <div className={styles.detailPanel}>
          <div className={styles.panelHeader}>
            <h3 className={styles.sectionTitle}>最近の発注</h3>
          </div>
          <div className={styles.panelBody}>
            {recentOrders.length > 0 ? (
              <table className={styles.simpleTable}>
                <thead>
                  <tr>
                    <th>発注番号</th>
                    <th>サプライヤー</th>
                    <th>発注日</th>
                    <th>金額</th>
                    <th>ステータス</th>
                  </tr>
                </thead>
                <tbody>
                  {recentOrders.map((order) => (
                    <tr key={order.id} className={styles.clickableRow}>
                      <td className={styles.orderNumber}>{order.orderNumber}</td>
                      <td>{order.supplierName}</td>
                      <td>{formatDate(order.orderDate)}</td>
                      <td className={styles.amount}>{formatCurrency(order.totalAmount)}</td>
                      <td>
                        <span className={`${styles.statusTag} ${styles[STATUS_CLASSES[order.status] || 'statusDefault']}`}>
                          {STATUS_LABELS[order.status] || order.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <div className={styles.emptyState}>最近の発注はありません</div>
            )}
          </div>
        </div>

        <div className={styles.detailPanel}>
          <div className={styles.panelHeader}>
            <h3 className={styles.sectionTitle}>在庫アラート</h3>
          </div>
          <div className={styles.panelBody}>
            {lowStockItems.length > 0 ? (
              <div className={styles.alertList}>
                {lowStockItems.map((item) => (
                  <div key={item.id} className={styles.alertItem}>
                    <div className={styles.alertItemInfo}>
                      <span className={styles.alertProductName}>{item.productName}</span>
                      <span className={styles.alertProductSku}>{item.productSku}</span>
                    </div>
                    <div className={styles.alertItemStock}>
                      <div className={styles.stockValues}>
                        <span className={`${styles.currentStock} ${item.quantity <= item.minimumStock / 2 ? styles.critical : ''}`}>
                          現在: {item.quantity}
                        </span>
                        <span className={styles.minimumStock}>最低: {item.minimumStock}</span>
                      </div>
                      <div className={styles.stockBar}>
                        <div
                          className={`${styles.stockBarFill} ${item.quantity <= item.minimumStock / 2 ? styles.stockCritical : styles.stockWarning}`}
                          style={{ width: `${item.minimumStock > 0 ? Math.min((item.quantity / item.minimumStock) * 100, 100) : 0}%` }}
                        />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className={styles.emptyState}>在庫アラートはありません</div>
            )}
          </div>
        </div>
      </section>
    </div>
  )
}

// migrated/migrated-frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import {
  DashboardService,
  DashboardSummary,
  SpendingTrendItem,
  CategorySpendingItem,
  PurchaseOrderResponse,
  InventoryAlertItem,
  BudgetDto,
} from '../../core/services/dashboard.service';

interface CategorySpendingDisplay extends CategorySpendingItem {
  percentage: number;
}

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
})
export class DashboardComponent implements OnInit {
  isLoading = true;

  // Summary
  totalOrders = 0;
  pendingOrderCount = 0;
  approvedOrderCount = 0;
  lowStockCount = 0;
  pendingApprovals = 0;

  // Budget
  budgetTotal = 0;
  budgetSpent = 0;
  budgetUtilization = 0;

  // Charts
  monthlySpending: SpendingTrendItem[] = [];
  categorySpending: CategorySpendingDisplay[] = [];

  // Tables
  recentOrders: PurchaseOrderResponse[] = [];
  lowStockItems: InventoryAlertItem[] = [];

  private readonly STATUS_LABELS: Record<string, string> = {
    DRAFT: '下書き',
    SUBMITTED: '申請中',
    APPROVED: '承認済み',
    ORDERED: '発注済み',
    REJECTED: '却下',
    CANCELLED: 'キャンセル',
    DELIVERED: '納品済み',
    COMPLETED: '完了',
  };

  private readonly STATUS_CLASSES: Record<string, string> = {
    DRAFT: 'status-draft',
    SUBMITTED: 'status-pending',
    APPROVED: 'status-approved',
    ORDERED: 'status-ordered',
    REJECTED: 'status-rejected',
    CANCELLED: 'status-cancelled',
    DELIVERED: 'status-delivered',
    COMPLETED: 'status-completed',
  };

  constructor(
    private dashboardService: DashboardService,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.loadDashboardData();
  }

  private loadDashboardData(): void {
    this.isLoading = true;

    // Load summary
    this.dashboardService.getSummary().subscribe({
      next: (summary) => {
        this.lowStockCount = summary.lowStockItems;
        this.pendingApprovals = summary.pendingApprovals;
      },
      error: () => {},
    });

    // Load spending trend
    this.dashboardService.getSpendingTrend().subscribe({
      next: (data) => {
        this.monthlySpending = data;
      },
      error: () => {
        this.monthlySpending = [];
      },
    });

    // Load category spending
    this.dashboardService.getCategorySpending().subscribe({
      next: (data) => {
        const totalCategorySpending = data.reduce((sum, cat) => sum + cat.totalAmount, 0);
        this.categorySpending = data.map((cat) => ({
          ...cat,
          percentage:
            totalCategorySpending > 0
              ? Math.round((cat.totalAmount / totalCategorySpending) * 100)
              : 0,
        }));
      },
      error: () => {
        this.categorySpending = [];
      },
    });

    // Load purchase orders
    this.dashboardService.getPurchaseOrders().subscribe({
      next: (result) => {
        this.totalOrders = result.totalElements;
        this.pendingOrderCount = result.content.filter((o) => o.status === 'SUBMITTED').length;
        this.approvedOrderCount = result.content.filter((o) => o.status === 'APPROVED').length;
        this.recentOrders = result.content
          .sort((a, b) => new Date(b.orderDate).getTime() - new Date(a.orderDate).getTime())
          .slice(0, 10);
      },
      error: () => {
        this.recentOrders = [];
      },
    });

    // Load low stock alerts
    this.dashboardService.getLowStockAlerts().subscribe({
      next: (data) => {
        this.lowStockItems = data;
        this.lowStockCount = data.length;
      },
      error: () => {
        this.lowStockItems = [];
      },
    });

    // Load budgets
    this.dashboardService.getBudgets().subscribe({
      next: (budgets) => {
        this.budgetTotal = budgets.reduce((sum, b) => sum + b.totalAmount, 0);
        this.budgetSpent = budgets.reduce((sum, b) => sum + b.usedAmount, 0);
        this.budgetUtilization =
          this.budgetTotal > 0 ? Math.round((this.budgetSpent / this.budgetTotal) * 100) : 0;
      },
      error: () => {},
    });

    // Load requisitions (used by current system's dashboard network calls)
    this.dashboardService.getRequisitions(0, 100, 'PENDING_APPROVAL').subscribe({
      next: () => {
        this.isLoading = false;
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  formatDate(dateStr: string): string {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}年${month}月${day}日`;
  }

  formatCurrency(amount: number): string {
    if (amount == null) return '¥0';
    return '¥' + amount.toLocaleString('ja-JP');
  }

  getStatusLabel(status: string): string {
    return this.STATUS_LABELS[status] || status;
  }

  getStatusClass(status: string): string {
    return this.STATUS_CLASSES[status] || 'status-default';
  }

  getBarHeight(amount: number): number {
    if (!this.monthlySpending || this.monthlySpending.length === 0) return 0;
    const maxAmount = Math.max(...this.monthlySpending.map((s) => s.amount));
    if (maxAmount === 0) return 0;
    return Math.round((amount / maxAmount) * 150);
  }

  navigateToOrders(): void {
    this.router.navigate(['/procurement/orders']);
  }

  navigateToOrder(orderId: number): void {
    this.router.navigate(['/procurement/orders', orderId]);
  }

  navigateToInventory(): void {
    this.router.navigate(['/inventory']);
  }

  navigateToTasks(): void {
    this.router.navigate(['/dashboard/tasks']);
  }

  navigateToProduct(productId: number): void {
    this.router.navigate(['/products', productId]);
  }
}

<div class="dashboard-container" *ngIf="!isLoading">
  <h1>ダッシュボード</h1>
  <!-- Summary Cards -->
  <section class="summary-cards">
    <!-- Card 1: Orders -->
    <div class="summary-card card-orders" (click)="navigateToOrders()">
      <div class="card-header">
        <h3 class="card-title">発注件数</h3>
        <span class="card-icon icon-orders">&#x1f4e6;</span>
      </div>
      <div class="card-body">
        <div class="card-main-value">{{ totalOrders }}件</div>
        <div class="card-sub-values">
          <div class="sub-value">
            <span class="sub-label">保留中</span>
            <span class="sub-count pending">{{ pendingOrderCount }}</span>
          </div>
          <div class="sub-value">
            <span class="sub-label">承認済み</span>
            <span class="sub-count approved">{{ approvedOrderCount }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Card 2: Stock Alerts -->
    <div class="summary-card card-stock" (click)="navigateToInventory()">
      <div class="card-header">
        <h3 class="card-title">在庫アラート</h3>
        <span class="card-icon icon-alert">&#x26a0;&#xfe0f;</span>
      </div>
      <div class="card-body">
        <div class="card-main-value" [class.has-alert]="lowStockCount > 0">{{ lowStockCount }}</div>
        <div class="card-description">在庫不足の製品があります</div>
      </div>
    </div>

    <!-- Card 3: Pending Approvals -->
    <div class="summary-card card-approvals" (click)="navigateToTasks()">
      <div class="card-header">
        <h3 class="card-title">承認待ち</h3>
        <span class="card-icon icon-approval">&#x2705;</span>
      </div>
      <div class="card-body">
        <div class="card-main-value" [class.has-pending]="pendingApprovals > 0">
          {{ pendingApprovals }}
        </div>
        <div class="card-description">承認が必要なタスク</div>
      </div>
    </div>

    <!-- Card 4: Budget -->
    <div class="summary-card card-budget">
      <div class="card-header">
        <h3 class="card-title">予算消化率</h3>
        <span class="card-icon icon-budget">&#x1f4b0;</span>
      </div>
      <div class="card-body">
        <div class="card-main-value">{{ budgetUtilization }}%</div>
        <div class="budget-bar">
          <div
            class="budget-bar-fill"
            [style.width.%]="budgetUtilization"
            [class.budget-warning]="budgetUtilization > 80 && budgetUtilization <= 95"
            [class.budget-danger]="budgetUtilization > 95"
          ></div>
        </div>
        <div class="budget-detail">
          {{ formatCurrency(budgetSpent) }} / {{ formatCurrency(budgetTotal) }}
        </div>
      </div>
    </div>
  </section>

  <!-- Charts Section -->
  <section class="charts-section">
    <!-- Monthly Spending Trend -->
    <div class="chart-container">
      <h3 class="section-title">月別発注金額推移</h3>
      <div class="chart-placeholder bar-chart">
        <div class="chart-bars" *ngIf="monthlySpending.length > 0">
          <div class="chart-bar-wrapper" *ngFor="let item of monthlySpending">
            <div class="chart-bar" [style.height.px]="getBarHeight(item.amount)"></div>
            <span class="chart-bar-label">{{ item.month }}</span>
          </div>
        </div>
        <div class="chart-note" *ngIf="monthlySpending.length === 0">データがありません</div>
      </div>
    </div>

    <!-- Category Spending -->
    <div class="chart-container">
      <h3 class="section-title">カテゴリ別支出割合</h3>
      <div class="category-list">
        <div class="category-item" *ngFor="let cat of categorySpending">
          <div class="category-bar-container">
            <span class="category-name">{{ cat.categoryName }}</span>
            <div class="category-bar">
              <div class="category-bar-fill" [style.width.%]="cat.percentage"></div>
            </div>
          </div>
          <span class="category-percentage">{{ cat.percentage }}%</span>
          <span class="category-amount">{{ formatCurrency(cat.totalAmount) }}</span>
        </div>
      </div>
    </div>
  </section>

  <!-- Detail Section (Tables) -->
  <section class="detail-section">
    <!-- Recent Orders -->
    <div class="detail-panel recent-orders">
      <div class="panel-header">
        <h3 class="section-title">最近の発注</h3>
        <a class="link-more" routerLink="/procurement/orders">すべて表示 &rarr;</a>
      </div>
      <div class="panel-body">
        <table class="simple-table" *ngIf="recentOrders.length > 0">
          <thead>
            <tr>
              <th>発注番号</th>
              <th>サプライヤー</th>
              <th>発注日</th>
              <th>金額</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <tr
              class="clickable-row"
              *ngFor="let order of recentOrders"
              (click)="navigateToOrder(order.id)"
            >
              <td class="order-number">{{ order.orderNumber }}</td>
              <td>{{ order.supplierName }}</td>
              <td>{{ formatDate(order.orderDate) }}</td>
              <td class="amount">{{ formatCurrency(order.totalAmount) }}</td>
              <td>
                <span class="status-tag" [ngClass]="getStatusClass(order.status)">
                  {{ getStatusLabel(order.status) }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="empty-state" *ngIf="recentOrders.length === 0">
          <p>最近の発注はありません</p>
        </div>
      </div>
    </div>

    <!-- Stock Alerts -->
    <div class="detail-panel stock-alerts">
      <div class="panel-header">
        <h3 class="section-title">在庫アラート</h3>
        <a class="link-more" routerLink="/inventory">すべて表示 &rarr;</a>
      </div>
      <div class="panel-body">
        <div class="alert-list" *ngIf="lowStockItems.length > 0">
          <div
            class="alert-item"
            *ngFor="let item of lowStockItems"
            (click)="navigateToProduct(item.productId)"
          >
            <div class="alert-item-info">
              <span class="alert-product-name">{{ item.productName }}</span>
              <span class="alert-product-sku">{{ item.productSku }}</span>
            </div>
            <div class="alert-item-stock">
              <div class="stock-values">
                <span
                  class="current-stock"
                  [class.critical]="item.quantityOnHand <= item.minimumStock / 2"
                  >現在: {{ item.quantityOnHand }}</span
                >
                <span class="minimum-stock">最低: {{ item.minimumStock }}</span>
              </div>
              <div class="stock-bar">
                <div
                  class="stock-bar-fill"
                  [style.width.%]="(item.quantityOnHand / item.minimumStock) * 100"
                  [class.stock-critical]="item.quantityOnHand <= item.minimumStock * 0.3"
                  [class.stock-warning]="
                    item.quantityOnHand > item.minimumStock * 0.3 &&
                    item.quantityOnHand <= item.minimumStock
                  "
                ></div>
              </div>
            </div>
          </div>
        </div>
        <div class="empty-state" *ngIf="lowStockItems.length === 0">
          <p>在庫アラートはありません</p>
        </div>
      </div>
    </div>
  </section>
</div>
