// migrated/migrated-frontend/src/app/features/products/product-detail/product-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProductService } from '../services/product.service';
import { ProductDetailResponse, ProductResponse, STATUS_LABELS } from '../models/product.model';

interface SpecificationRow {
  key: string;
  value: string;
}

interface ProductImage {
  id: number;
  url: string;
  altText: string;
  isPrimary: boolean;
}

interface AlternativeProduct {
  id: number;
  sku: string;
  name: string;
  unitPrice: number;
  status: string;
  manufacturerName: string;
}

interface ProductDocumentView {
  id: number;
  fileName: string;
  filePath: string;
  fileType: string;
  fileSize: number;
  uploadedBy: string;
  uploadedAt: string;
}

interface ChangeLogEntry {
  id: number;
  field: string;
  oldValue: string;
  newValue: string;
  changedBy: string;
  changedAt: string;
}

@Component({
  selector: 'app-product-detail',
  templateUrl: './product-detail.component.html',
  styleUrls: ['./product-detail.component.scss'],
})
export class ProductDetailComponent implements OnInit {
  productId!: number;
  product: ProductDetailResponse | null = null;
  isLoading = true;
  errorMessage = '';
  activeTab = 0;

  tabs = [
    { label: '基本情報' },
    { label: '仕様' },
    { label: '画像' },
    { label: '代替品' },
    { label: 'サプライヤー' },
    { label: 'ドキュメント' },
    { label: '変更履歴' },
  ];

  specifications: SpecificationRow[] = [];
  productImages: ProductImage[] = [];
  alternativeProducts: AlternativeProduct[] = [];
  productSuppliers: any[] = [];
  documents: ProductDocumentView[] = [];
  changeLog: ChangeLogEntry[] = [];
  showDeleteConfirm = false;

  totalStock = 0;
  totalReserved = 0;
  totalAvailable = 0;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private productService: ProductService,
  ) {}

  ngOnInit(): void {
    this.productId = Number(this.route.snapshot.paramMap.get('id'));
    this.loadProduct();
  }

  private loadProduct(): void {
    this.isLoading = true;
    this.productService.getProduct(this.productId).subscribe({
      next: (product) => {
        this.product = product;
        this.parseSpecifications(product);
        this.loadImages(product);
        this.loadDocuments(product);
        this.loadAlternativeProducts();
        this.loadChangeLog();
        this.totalStock = product.totalStock ?? 0;
        this.totalReserved = product.totalReserved ?? 0;
        this.totalAvailable = product.totalAvailable ?? 0;
        this.isLoading = false;
      },
      error: () => {
        this.errorMessage = '製品情報の取得に失敗しました。';
        this.isLoading = false;
      },
    });
  }

  private parseSpecifications(product: ProductDetailResponse): void {
    try {
      if (product.specifications) {
        const specs = JSON.parse(product.specifications);
        this.specifications = Object.keys(specs).map((key) => ({
          key,
          value: specs[key],
        }));
      }
    } catch {
      this.specifications = [];
    }
  }

  private loadImages(product: ProductDetailResponse): void {
    if (product.images && product.images.length > 0) {
      this.productImages = product.images.map((img, i) => ({
        id: img.id || i + 1,
        url: img.fileName || '/assets/images/no-image.png',
        altText: product.name + (img.primary ? ' - メイン画像' : ' - サブ画像'),
        isPrimary: img.primary || false,
      }));
    } else {
      this.productImages = [
        {
          id: 0,
          url: '/assets/images/no-image.png',
          altText: '画像なし - No Image',
          isPrimary: true,
        },
      ];
    }
  }

  private loadDocuments(product: ProductDetailResponse): void {
    if (product.documents && product.documents.length > 0) {
      this.documents = product.documents.map((doc, i) => ({
        id: doc.id || i + 1,
        fileName: doc.fileName || 'unknown',
        filePath: doc.filePath || '',
        fileType: doc.fileName?.endsWith('.pdf') ? 'application/pdf' : 'application/octet-stream',
        fileSize: 0,
        uploadedBy: '-',
        uploadedAt: '',
      }));
    } else {
      this.documents = [];
    }
  }

  private loadAlternativeProducts(): void {
    this.productService.getProducts({ page: 0, size: 5 }).subscribe({
      next: (result) => {
        this.alternativeProducts = result.content
          .filter((p) => p.id !== this.productId)
          .map((p) => ({
            id: p.id,
            sku: p.sku,
            name: p.name,
            unitPrice: p.unitPrice ?? 0,
            status: p.status,
            manufacturerName: p.manufacturerName ?? '',
          }));
      },
      error: () => {},
    });
  }

  private loadChangeLog(): void {
    this.productService.getProductChangeLog(this.productId).subscribe({
      next: (entries) => {
        this.changeLog = entries.map((e) => ({
          id: e.id,
          field: e.field,
          oldValue: e.oldValue ?? '-',
          newValue: e.newValue ?? '-',
          changedBy: e.changedBy ?? '-',
          changedAt: e.changedAt ?? '',
        }));
      },
      error: () => {},
    });
  }

  switchTab(index: number): void {
    this.activeTab = index;
  }

  navigateToList(): void {
    this.router.navigate(['/products']);
  }

  navigateToEdit(): void {
    this.router.navigate(['/products', this.productId, 'edit']);
  }

  navigateToAlternative(productId: number): void {
    this.router.navigate(['/products', productId]);
  }

  navigateToSupplier(supplierId: number): void {
    this.router.navigate(['/suppliers', supplierId]);
  }

  confirmDelete(): void {
    this.showDeleteConfirm = true;
  }

  deleteProduct(): void {
    this.productService.deleteProduct(this.productId).subscribe({
      next: () => this.navigateToList(),
      error: () => {
        this.errorMessage = '製品の削除に失敗しました。';
      },
    });
  }

  cancelDelete(): void {
    this.showDeleteConfirm = false;
  }

  downloadDocument(doc: ProductDocumentView): void {
    if (doc.filePath) {
      const a = document.createElement('a');
      a.href = doc.filePath;
      a.download = doc.fileName || 'document.pdf';
      a.target = '_blank';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }
  }

  getStatusLabel(status: string): string {
    return STATUS_LABELS[status] || status;
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'ACTIVE':
        return 'status-active';
      case 'INACTIVE':
        return 'status-inactive';
      case 'DISCONTINUED':
        return 'status-discontinued';
      case 'PENDING':
        return 'status-pending';
      default:
        return '';
    }
  }

  get dimensions(): string {
    if (!this.product) return '-';
    const w = this.product.width;
    const h = this.product.height;
    const d = this.product.depth;
    if (w == null && h == null && d == null) return '-';
    return `${w ?? '-'} × ${h ?? '-'} × ${d ?? '-'} mm`;
  }

  formatCurrency(amount: number | null): string {
    if (amount == null) return '¥0';
    return '¥' + amount.toLocaleString('ja-JP');
  }

  formatDateTime(dateStr: string | null): string {
    if (!dateStr) return '-';
    const d = new Date(dateStr);
    return (
      d.getFullYear() +
      '/' +
      ('0' + (d.getMonth() + 1)).slice(-2) +
      '/' +
      ('0' + d.getDate()).slice(-2) +
      ' ' +
      ('0' + d.getHours()).slice(-2) +
      ':' +
      ('0' + d.getMinutes()).slice(-2)
    );
  }

  formatFileSize(bytes: number): string {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }

  formatDate(dateStr: string): string {
    if (!dateStr) return '-';
    const d = new Date(dateStr);
    return (
      d.getFullYear() +
      '/' +
      ('0' + (d.getMonth() + 1)).slice(-2) +
      '/' +
      ('0' + d.getDate()).slice(-2)
    );
  }
}

<h1>製品詳細</h1>

<div class="loading-spinner" *ngIf="isLoading">
  <div class="spinner"></div>
</div>

<!-- エラーメッセージ -->
<div class="error-banner" *ngIf="errorMessage">
  <span>{{ errorMessage }}</span>
  <button class="btn-back" (click)="navigateToList()">一覧に戻る</button>
</div>

<div class="detail-container" *ngIf="!isLoading && product">
  <!-- ヘッダー部分 -->
  <div class="detail-header">
    <div class="header-info">
      <div class="product-title-row">
        <h2 class="product-name">{{ product.name }}</h2>
        <span class="status-badge" [ngClass]="getStatusClass(product.status)">{{
          getStatusLabel(product.status)
        }}</span>
      </div>
      <div class="product-meta">
        <span class="meta-item">SKU: {{ product.sku }}</span>
        <span class="meta-item">カテゴリ: {{ product.categoryName }}</span>
        <span class="meta-item">メーカー: {{ product.manufacturerName }}</span>
      </div>
    </div>
    <div class="header-actions">
      <button class="btn-secondary" (click)="navigateToList()">← 一覧に戻る</button>
      <button class="btn-primary" (click)="navigateToEdit()">編集</button>
      <button class="btn-danger" (click)="confirmDelete()">削除</button>
    </div>
  </div>

  <!-- タブナビゲーション -->
  <div class="tab-navigation">
    <button
      *ngFor="let tab of tabs; let i = index"
      class="tab-button"
      [class.active]="activeTab === i"
      (click)="switchTab(i)"
    >
      {{ tab.label }}
    </button>
  </div>

  <!-- タブコンテンツ -->
  <div class="tab-content">
    <!-- 基本情報タブ -->
    <div class="tab-panel" *ngIf="activeTab === 0">
      <div class="info-grid">
        <div class="info-section">
          <h4 class="section-subtitle">基本情報</h4>
          <table class="info-table">
            <tr>
              <th>製品名</th>
              <td>{{ product.name }}</td>
            </tr>
            <tr>
              <th>SKU</th>
              <td class="mono">{{ product.sku }}</td>
            </tr>
            <tr>
              <th>説明</th>
              <td>{{ product.description || '-' }}</td>
            </tr>
            <tr>
              <th>カテゴリ</th>
              <td>{{ product.categoryName }}</td>
            </tr>
            <tr>
              <th>メーカー</th>
              <td>{{ product.manufacturerName }}</td>
            </tr>
            <tr>
              <th>ステータス</th>
              <td>
                <span class="status-tag" [ngClass]="getStatusClass(product.status)">
                  {{ getStatusLabel(product.status) }}
                </span>
              </td>
            </tr>
          </table>
        </div>

        <div class="info-section">
          <h4 class="section-subtitle">価格・数量</h4>
          <table class="info-table">
            <tr>
              <th>単価</th>
              <td class="amount">{{ formatCurrency(product.unitPrice) }}</td>
            </tr>
            <tr>
              <th>単位</th>
              <td>{{ product.unit || '-' }}</td>
            </tr>
            <tr>
              <th>最低発注数</th>
              <td>{{ product.minimumOrderQuantity }}</td>
            </tr>
            <tr>
              <th>リードタイム</th>
              <td>{{ product.leadTimeDays }} 日</td>
            </tr>
          </table>
        </div>

        <div class="info-section">
          <h4 class="section-subtitle">物理情報</h4>
          <table class="info-table">
            <tr>
              <th>重量</th>
              <td>{{ product.weight ? product.weight + ' kg' : '-' }}</td>
            </tr>
            <tr>
              <th>寸法</th>
              <td>{{ dimensions }}</td>
            </tr>
          </table>
        </div>

        <div class="info-section">
          <h4 class="section-subtitle">在庫状況</h4>
          <div class="stock-summary">
            <div class="stock-item">
              <span class="stock-label">合計在庫</span>
              <span class="stock-value">{{ totalStock }}</span>
            </div>
            <div class="stock-item">
              <span class="stock-label">予約済み</span>
              <span class="stock-value reserved">{{ totalReserved }}</span>
            </div>
            <div class="stock-item">
              <span class="stock-label">利用可能</span>
              <span class="stock-value available">{{ totalAvailable }}</span>
            </div>
          </div>
          <table
            class="data-table"
            *ngIf="product.inventoryItems && product.inventoryItems.length > 0"
          >
            <thead>
              <tr>
                <th>倉庫</th>
                <th>在庫数</th>
                <th>予約</th>
                <th>利用可能</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let inv of product.inventoryItems">
                <td>{{ inv.warehouseName }}</td>
                <td>{{ inv.quantity }}</td>
                <td>{{ inv.reservedQuantity }}</td>
                <td>{{ inv.availableQuantity }}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="info-section full-width">
          <h4 class="section-subtitle">管理情報</h4>
          <table class="info-table">
            <tr>
              <th>登録日</th>
              <td>{{ formatDateTime(product.createdAt) }}</td>
            </tr>
            <tr>
              <th>最終更新日</th>
              <td>{{ formatDateTime(product.updatedAt) }}</td>
            </tr>
            <tr>
              <th>備考</th>
              <td>{{ product.notes || '-' }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>

    <!-- 仕様タブ -->
    <div class="tab-panel" *ngIf="activeTab === 1">
      <table class="spec-table" *ngIf="specifications.length > 0">
        <thead>
          <tr>
            <th>項目</th>
            <th>値</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let spec of specifications">
            <td class="spec-key">{{ spec.key }}</td>
            <td>{{ spec.value }}</td>
          </tr>
        </tbody>
      </table>
      <div class="empty-state" *ngIf="specifications.length === 0">
        <p class="empty-message">仕様情報は登録されていません</p>
      </div>
    </div>

    <!-- 画像タブ -->
    <div class="tab-panel" *ngIf="activeTab === 2">
      <div class="image-grid" *ngIf="productImages.length > 0">
        <div class="image-card" *ngFor="let img of productImages" [class.primary]="img.isPrimary">
          <div class="image-wrapper">
            <img
              [src]="img.url"
              [alt]="img.altText"
              class="product-image"
              onerror="this.src='/assets/images/no-image.png'"
            />
            <span class="primary-badge" *ngIf="img.isPrimary">メイン</span>
          </div>
          <p class="image-alt">{{ img.altText }}</p>
        </div>
      </div>
      <div class="empty-state" *ngIf="productImages.length === 0">
        <p class="empty-message">画像は登録されていません</p>
      </div>
    </div>

    <!-- 代替品タブ -->
    <div class="tab-panel" *ngIf="activeTab === 3">
      <table class="data-table" *ngIf="alternativeProducts.length > 0">
        <thead>
          <tr>
            <th>SKU</th>
            <th>製品名</th>
            <th>メーカー</th>
            <th>単価</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let alt of alternativeProducts">
            <td class="mono">{{ alt.sku }}</td>
            <td>{{ alt.name }}</td>
            <td>{{ alt.manufacturerName }}</td>
            <td class="amount">{{ formatCurrency(alt.unitPrice) }}</td>
            <td>
              <span class="status-tag" [ngClass]="getStatusClass(alt.status)">
                {{ getStatusLabel(alt.status) }}
              </span>
            </td>
            <td>
              <button class="btn-link" (click)="navigateToAlternative(alt.id)">詳細</button>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="empty-state" *ngIf="alternativeProducts.length === 0">
        <p class="empty-message">代替品は登録されていません</p>
      </div>
    </div>

    <!-- サプライヤータブ -->
    <div class="tab-panel" *ngIf="activeTab === 4">
      <table class="data-table" *ngIf="productSuppliers.length > 0">
        <thead>
          <tr>
            <th>サプライヤー名</th>
            <th>サプライヤーSKU</th>
            <th>単価</th>
            <th>リードタイム</th>
            <th>優先</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let sup of productSuppliers" [class.preferred]="sup.isPreferred">
            <td>{{ sup.supplierName }}</td>
            <td class="mono">{{ sup.supplierSku }}</td>
            <td class="amount">{{ formatCurrency(sup.unitPrice) }}</td>
            <td>{{ sup.leadTimeDays }} 日</td>
            <td>
              <span class="preferred-badge" *ngIf="sup.isPreferred">優先</span>
            </td>
            <td>
              <button class="btn-link" (click)="navigateToSupplier(sup.supplierId)">詳細</button>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="empty-state" *ngIf="productSuppliers.length === 0">
        <span class="empty-icon">&#128196;</span>
        <p class="empty-message">サプライヤー情報は登録されていません</p>
      </div>
    </div>

    <!-- ドキュメントタブ -->
    <div class="tab-panel" *ngIf="activeTab === 5">
      <div class="document-list" *ngIf="documents.length > 0">
        <div class="document-item" *ngFor="let doc of documents">
          <div class="document-icon">
            <span class="file-type-icon">{{ doc.fileType.includes('pdf') ? 'PDF' : 'DOC' }}</span>
          </div>
          <div class="document-info">
            <span class="document-name">{{ doc.fileName }}</span>
            <span class="document-meta">
              {{ formatFileSize(doc.fileSize) }} | {{ doc.uploadedBy }} |
              {{ formatDate(doc.uploadedAt) }}
            </span>
          </div>
          <div class="document-actions">
            <button class="btn-link" (click)="downloadDocument(doc)">ダウンロード</button>
          </div>
        </div>
      </div>
      <div class="empty-state" *ngIf="documents.length === 0">
        <p class="empty-message">ドキュメントは登録されていません</p>
      </div>
    </div>

    <!-- 変更履歴タブ -->
    <div class="tab-panel" *ngIf="activeTab === 6">
      <div class="changelog" *ngIf="changeLog.length > 0">
        <div class="changelog-entry" *ngFor="let entry of changeLog">
          <div class="changelog-timeline">
            <div class="timeline-dot"></div>
            <div class="timeline-line"></div>
          </div>
          <div class="changelog-content">
            <div class="changelog-header">
              <span class="changelog-field">{{ entry.field }}</span>
              <span class="changelog-date">{{ formatDateTime(entry.changedAt) }}</span>
            </div>
            <div class="changelog-values">
              <span class="old-value" *ngIf="entry.oldValue !== '-'">{{ entry.oldValue }}</span>
              <span class="arrow" *ngIf="entry.oldValue !== '-'">→</span>
              <span class="new-value">{{ entry.newValue }}</span>
            </div>
            <span class="changelog-user">{{ entry.changedBy }}</span>
          </div>
        </div>
      </div>
      <div class="empty-state" *ngIf="changeLog.length === 0">
        <p class="empty-message">変更履歴はありません</p>
      </div>
    </div>
  </div>
</div>

<!-- 削除確認ダイアログ -->
<div class="confirm-dialog-overlay" *ngIf="showDeleteConfirm" (click)="cancelDelete()">
  <div class="confirm-dialog" (click)="$event.stopPropagation()">
    <h3 class="dialog-title">製品の削除</h3>
    <div class="dialog-body">
      <p>この製品を削除してもよろしいですか？この操作は取り消せません。</p>
    </div>
    <div class="dialog-footer">
      <button class="btn-outline" (click)="cancelDelete()">キャンセル</button>
      <button class="btn-primary" (click)="deleteProduct()">削除する</button>
    </div>
  </div>
</div>

// proquip_new/frontend/src/components/ProductDetail.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import styles from './ProductDetail.module.css'

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8280'

interface ProductData {
  id: number; sku: string; name: string; description: string
  categoryName: string; manufacturerName: string; unitPrice: number
  status: string; unit: string; minimumOrderQuantity: number
  leadTimeDays: number; weight: number | null; dimensions: string | null
  notes: string | null; createdAt: string; updatedAt: string
  modelNumber: string | null; barcode: string | null
  specifications: { key: string; value: string }[]
  images: { id: number; url: string; altText: string; isPrimary: boolean }[]
  inventoryItems: { warehouseName: string; quantity: number; reservedQuantity: number; availableQuantity: number }[]
  suppliers: { supplierId: number; supplierName: string; supplierSku: string; unitPrice: number; leadTimeDays: number; isPreferred: boolean }[]
  changeLog: { id: number; changeType: string; field: string; oldValue: string; newValue: string; changedAt: string; changedBy: string }[]
}

const STATUS_LABELS: Record<string, string> = {
  ACTIVE: '有効', INACTIVE: '無効', DISCONTINUED: '廃止', PENDING_APPROVAL: '承認待ち', DRAFT: '下書き',
}
const STATUS_CLASSES: Record<string, string> = {
  ACTIVE: 'statusActive', INACTIVE: 'statusInactive', DISCONTINUED: 'statusDiscontinued',
  PENDING_APPROVAL: 'statusPending', DRAFT: 'statusDraft',
}

function formatCurrency(n: number | null) { return n == null ? '¥0' : '¥' + n.toLocaleString('ja-JP') }
function formatDateTime(s: string | null) {
  if (!s) return '-'
  const d = new Date(s)
  if (isNaN(d.getTime())) return '-'
  return `${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`
}

const TABS = ['基本情報', '仕様', '画像', '在庫状況', 'サプライヤー', '変更履歴']

export function ProductDetail({ productId }: { productId: string }) {
  const router = useRouter()
  const [product, setProduct] = useState<ProductData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [activeTab, setActiveTab] = useState(0)

  useEffect(() => {
    fetch(`${API_BASE}/api/products/${productId}`)
      .then(r => { if (!r.ok) throw new Error(); return r.json() })
      .then(setProduct)
      .catch(() => setError('製品情報の取得に失敗しました。'))
      .finally(() => setLoading(false))
  }, [productId])

  if (loading) return <div className={styles.loading}>読み込み中...</div>
  if (error) return (
    <div className={styles.errorBanner}>
      <span>{error}</span>
      <button className={styles.btnBack} onClick={() => router.push('/products')}>一覧に戻る</button>
    </div>
  )
  if (!product) return null

  const totalStock = product.inventoryItems.reduce((s, i) => s + i.quantity, 0)
  const totalReserved = product.inventoryItems.reduce((s, i) => s + i.reservedQuantity, 0)
  const totalAvailable = product.inventoryItems.reduce((s, i) => s + i.availableQuantity, 0)

  return (
    <div>
      {/* ヘッダー */}
      <div className={styles.detailHeader}>
        <div className={styles.headerInfo}>
          <div className={styles.titleRow}>
            <h2 className={styles.productName}>{product.name}</h2>
            <span className={`${styles.statusTag} ${styles[STATUS_CLASSES[product.status] || 'statusDefault']}`}>
              {STATUS_LABELS[product.status] || product.status}
            </span>
          </div>
          <div className={styles.metaRow}>
            <span>SKU: {product.sku}</span>
            <span>カテゴリ: {product.categoryName}</span>
            <span>メーカー: {product.manufacturerName}</span>
          </div>
        </div>
        <div className={styles.headerActions}>
          <button className={styles.btnSecondary} onClick={() => router.push('/products')}>← 一覧に戻る</button>
        </div>
      </div>

      {/* タブ */}
      <div className={styles.tabNav}>
        {TABS.map((t, i) => (
          <button key={t} className={`${styles.tabBtn} ${activeTab === i ? styles.tabActive : ''}`}
            onClick={() => setActiveTab(i)}>{t}</button>
        ))}
      </div>

      <div className={styles.tabContent}>
        {/* 基本情報 */}
        {activeTab === 0 && (
          <div className={styles.infoGrid}>
            <div className={styles.infoSection}>
              <h4 className={styles.sectionSubtitle}>基本情報</h4>
              <table className={styles.infoTable}>
                <tbody>
                  <tr><th>製品名</th><td>{product.name}</td></tr>
                  <tr><th>SKU</th><td className={styles.mono}>{product.sku}</td></tr>
                  <tr><th>説明</th><td>{product.description || '-'}</td></tr>
                  <tr><th>カテゴリ</th><td>{product.categoryName}</td></tr>
                  <tr><th>メーカー</th><td>{product.manufacturerName}</td></tr>
                  <tr><th>ステータス</th><td>
                    <span className={`${styles.statusTag} ${styles[STATUS_CLASSES[product.status] || 'statusDefault']}`}>
                      {STATUS_LABELS[product.status] || product.status}
                    </span>
                  </td></tr>
                </tbody>
              </table>
            </div>
            <div className={styles.infoSection}>
              <h4 className={styles.sectionSubtitle}>価格・数量</h4>
              <table className={styles.infoTable}>
                <tbody>
                  <tr><th>単価</th><td className={styles.amount}>{formatCurrency(product.unitPrice)}</td></tr>
                  <tr><th>単位</th><td>{product.unit || '-'}</td></tr>
                  <tr><th>最低発注数</th><td>{product.minimumOrderQuantity}</td></tr>
                  <tr><th>リードタイム</th><td>{product.leadTimeDays} 日</td></tr>
                </tbody>
              </table>
            </div>
            <div className={styles.infoSection}>
              <h4 className={styles.sectionSubtitle}>物理情報</h4>
              <table className={styles.infoTable}>
                <tbody>
                  <tr><th>重量</th><td>{product.weight ? product.weight + ' kg' : '-'}</td></tr>
                  <tr><th>寸法</th><td>{product.dimensions || '-'}</td></tr>
                  {product.modelNumber && <tr><th>型番</th><td>{product.modelNumber}</td></tr>}
                  {product.barcode && <tr><th>バーコード</th><td className={styles.mono}>{product.barcode}</td></tr>}
                </tbody>
              </table>
            </div>
            <div className={styles.infoSection}>
              <h4 className={styles.sectionSubtitle}>在庫状況</h4>
              <div className={styles.stockSummary}>
                <div className={styles.stockItem}><span className={styles.stockLabel}>合計在庫</span><span className={styles.stockValue}>{totalStock}</span></div>
                <div className={styles.stockItem}><span className={styles.stockLabel}>予約済み</span><span className={`${styles.stockValue} ${styles.reserved}`}>{totalReserved}</span></div>
                <div className={styles.stockItem}><span className={styles.stockLabel}>利用可能</span><span className={`${styles.stockValue} ${styles.available}`}>{totalAvailable}</span></div>
              </div>
            </div>
            <div className={`${styles.infoSection} ${styles.fullWidth}`}>
              <h4 className={styles.sectionSubtitle}>管理情報</h4>
              <table className={styles.infoTable}>
                <tbody>
                  <tr><th>登録日</th><td>{formatDateTime(product.createdAt)}</td></tr>
                  <tr><th>最終更新日</th><td>{formatDateTime(product.updatedAt)}</td></tr>
                  <tr><th>備考</th><td>{product.notes || '-'}</td></tr>
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* 仕様 */}
        {activeTab === 1 && (
          product.specifications.length > 0 ? (
            <table className={styles.specTable}>
              <thead><tr><th>項目</th><th>値</th></tr></thead>
              <tbody>
                {product.specifications.map((s, i) => (
                  <tr key={i}><td className={styles.specKey}>{s.key}</td><td>{s.value}</td></tr>
                ))}
              </tbody>
            </table>
          ) : <div className={styles.emptyState}>仕様情報は登録されていません</div>
        )}

        {/* 画像 */}
        {activeTab === 2 && (
          product.images.length > 0 ? (
            <div className={styles.imageGrid}>
              {product.images.map(img => (
                <div key={img.id} className={`${styles.imageCard} ${img.isPrimary ? styles.primary : ''}`}>
                  <div className={styles.imageWrapper}>
                    <div className={styles.imagePlaceholder}>{img.altText || 'No Image'}</div>
                    {img.isPrimary && <span className={styles.primaryBadge}>メイン</span>}
                  </div>
                </div>
              ))}
            </div>
          ) : <div className={styles.emptyState}>画像は登録されていません</div>
        )}

        {/* 在庫状況 */}
        {activeTab === 3 && (
          product.inventoryItems.length > 0 ? (
            <table className={styles.dataTable}>
              <thead><tr><th>倉庫</th><th>在庫数</th><th>予約</th><th>利用可能</th></tr></thead>
              <tbody>
                {product.inventoryItems.map((inv, i) => (
                  <tr key={i}>
                    <td>{inv.warehouseName}</td>
                    <td className={styles.number}>{inv.quantity}</td>
                    <td className={styles.number}>{inv.reservedQuantity}</td>
                    <td className={styles.number}>{inv.availableQuantity}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : <div className={styles.emptyState}>在庫情報はありません</div>
        )}

        {/* サプライヤー */}
        {activeTab === 4 && (
          product.suppliers.length > 0 ? (
            <table className={styles.dataTable}>
              <thead><tr><th>サプライヤー名</th><th>サプライヤーSKU</th><th>単価</th><th>リードタイム</th><th>優先</th></tr></thead>
              <tbody>
                {product.suppliers.map((s, i) => (
                  <tr key={i} className={s.isPreferred ? styles.preferred : ''}>
                    <td>{s.supplierName}</td>
                    <td className={styles.mono}>{s.supplierSku}</td>
                    <td className={styles.amount}>{formatCurrency(s.unitPrice)}</td>
                    <td>{s.leadTimeDays} 日</td>
                    <td>{s.isPreferred && <span className={styles.preferredBadge}>優先</span>}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : <div className={styles.emptyState}>サプライヤー情報は登録されていません</div>
        )}

        {/* 変更履歴 */}
        {activeTab === 5 && (
          product.changeLog.length > 0 ? (
            <div className={styles.changelog}>
              {product.changeLog.map(entry => (
                <div key={entry.id} className={styles.changelogEntry}>
                  <div className={styles.timeline}>
                    <div className={styles.timelineDot} />
                    <div className={styles.timelineLine} />
                  </div>
                  <div className={styles.changelogContent}>
                    <div className={styles.changelogHeader}>
                      <span className={styles.changelogField}>{entry.field}</span>
                      <span className={styles.changelogDate}>{formatDateTime(entry.changedAt)}</span>
                    </div>
                    <div className={styles.changelogValues}>
                      {entry.oldValue && entry.oldValue !== '-' && (
                        <><span className={styles.oldValue}>{entry.oldValue}</span><span className={styles.arrow}>→</span></>
                      )}
                      <span className={styles.newValue}>{entry.newValue}</span>
                    </div>
                    <span className={styles.changelogUser}>{entry.changedBy}</span>
                  </div>
                </div>
              ))}
            </div>
          ) : <div className={styles.emptyState}>変更履歴はありません</div>
        )}
      </div>
    </div>
  )
}
