// migrated/migrated-frontend/src/app/core/layout/sidebar.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';

interface MenuItem {
  icon: string;
  label: string;
  route: string;
}

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css'],
})
export class SidebarComponent {
  @Input() collapsed = false;

  menuItems: MenuItem[] = [
    { icon: '\u25A0', label: 'ダッシュボード', route: '/dashboard' },
    { icon: '\u2605', label: '製品カタログ', route: '/products' },
    { icon: '\u2666', label: 'サプライヤー', route: '/suppliers' },
    { icon: '\u270E', label: '調達管理', route: '/procurement' },
    { icon: '\u25A3', label: '在庫管理', route: '/inventory' },
    { icon: '\u2302', label: '倉庫管理', route: '/warehouses' },
    { icon: '\u00A5', label: '価格管理', route: '/pricing' },
    { icon: '\u2630', label: 'レポート', route: '/reports' },
    { icon: '\u2699', label: '管理者設定', route: '/admin' },
    { icon: '\u21F5', label: 'インポート/エクスポート', route: '/import-export' },
  ];

  constructor(private router: Router) {}

  isActive(route: string): boolean {
    return this.router.url.startsWith(route);
  }
}

<nav class="sidebar" [class.collapsed]="collapsed">
  <ul class="nav-list">
    <li *ngFor="let item of menuItems" class="nav-item" [class.active]="isActive(item.route)" [title]="item.label">
      <a [routerLink]="item.route">
        <span class="nav-icon">{{ item.icon }}</span>
        <span class="nav-label" *ngIf="!collapsed">{{ item.label }}</span>
      </a>
    </li>
  </ul>
  <div class="sidebar-footer">
    <div class="version-info" *ngIf="!collapsed">
      <span class="version-label">バージョン</span>
      <span class="version-number">v1.0.0</span>
    </div>
  </div>
</nav>

// proquip_new/frontend/src/components/Sidebar.tsx
'use client'

import { usePathname } from 'next/navigation'
import styles from './Sidebar.module.css'

const menuItems = [
  { label: 'ダッシュボード', route: '/', icon: '■' },
  { label: '製品カタログ', route: '/products', icon: '★' },
  { label: 'サプライヤー', route: '/suppliers', icon: '◆' },
  { label: '調達管理', route: '/procurement', icon: '✎' },
  { label: '在庫管理', route: '/inventory', icon: '▣' },
  { label: '倉庫管理', route: '/warehouses', icon: '⌂' },
  { label: '価格管理', route: '/pricing', icon: '¥' },
  { label: 'レポート', route: '/reports', icon: '☰' },
  { label: '管理者設定', route: '/admin', icon: '⚙' },
]

function isActive(route: string, pathname: string): boolean {
  if (route === '/') return pathname === '/'
  return pathname.startsWith(route)
}

export function Sidebar() {
  const pathname = usePathname()

  return (
    <nav className={styles.sidebar}>
      <ul className={styles.navList}>
        {menuItems.map((item) => (
          <li key={item.route} className={`${styles.navItem} ${isActive(item.route, pathname) ? styles.active : ''}`}>
            <a href={item.route} className={styles.navLink}>
              <span className={styles.navIcon}>{item.icon}</span>
              <span className={styles.navLabel}>{item.label}</span>
            </a>
          </li>
        ))}
      </ul>
      <div className={styles.sidebarFooter}>
        <span className={styles.version}>v2.0.0</span>
      </div>
    </nav>
  )
}
